# Refer https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: ci

# Execute workflow on push and pull request to any branch
on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "src/**"
      - "!**.stories.js"
      - "!**.mdx"

jobs:
  ci:
    if: github.event.pull_request.merged == true

    runs-on: ${{ matrix.os }}

    env:
      ACCOUNT_NAME: shota-kamezawa
      COPY_REPOSITORY: copy_repository

    strategy:
      matrix:
        node: [12]
        os: [ubuntu-latest]

    steps:
      - name: sync-repository
        uses: peter-evans/repository-dispatch@v1
        with:
          event-type: sync-repository
          repository: ${{ env.ACCOUNT_NAME }}/${{ env.COPY_REPOSITORY }}
          client-payload: '{ "ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "pr_url": "${{ github.event.pull_request.html_url }}", "pr_title": "${{ github.event.pull_request.title }}" }'
          token: ${{ github.token }}
